### ISSUE TITLE
Handle ultra widescreen

### ISSUE THREAD

**Issue by MattLish** [Wildlander-mod/Launcher#372]
Ultra widescreen resolutions will not look correct.

Any ultra-widescreen resolution needs to be removed and if the user's screen is an ultrawide, then borderlessUpscaling needs to be disabled

**Comment by Dylan-Perry** [comment]
Settings to set: tickbox enable should make `borderlessUpscale = true`, tickbox disabled should be `borderlessUpscale = false`
