### ISSUE TITLE
Unlock MO2 GUI when launching from launcher to avoid MO2 "waiting for close" pop-up

### ISSUE THREAD

**Issue by Dylan-Perry** [Wildlander-mod/Launcher#389]
This can be accomplished by setting `lock_gui=true` in ModOrganizer.ini, and setting `lock_gui=false` when launching MO2 from within the launcher.

The setting should also probably return to `false` when exiting the launcher in general, in case users launch their MO2 instance from outside the launcher.

**Comment by MattLish** [comment]
We should be able to just reset it once MO2/Skyrim close
