### ISSUE TITLE
Copy ENB files on initial/default profile selection

### ISSUE THREAD

**Issue by TaranRoth** [Wildlander-mod/Launcher#434]
Currently, the user is forced to switch from and back to their preferred preset for the files to be copied over, the files should be copied for users using the default profile without switching the profile

**Comment by MattLish** [comment]
This shouldn't be the case. ENB files are supposed to be synced when the user first selects the modpack.

https://github.com/Wildlander-mod/Launcher/blob/3e3486aec14a68393e37127a9626179c45d70210/src/main/modpack.ts#L5-L5

https://github.com/Wildlander-mod/Launcher/blob/3e3486aec14a68393e37127a9626179c45d70210/src/main/ipcHandler.ts#L28-L28

Is this not happening for some users? Do _all_ users need to select an ENB for it to work?
