### ISSUE TITLE
Launcher freezes when switching to no shaders while no ENB files are in Stock Game folder

### ISSUE THREAD

**Issue by TaranRoth** [Wildlander-mod/Launcher#435]
Likely caused by launcher trying to delete nonexistent files, the easiest fix would be to simply check if the files exist before attempting to delete them.

**Comment by MattLish** [comment]
I am curious what scenario causes this.
ENBs are copied when the modpack is selected and when they are changed. If the user has selected noENB, then nothing is synced anyway. 
I guess this could happen if a user has manually removed them.

**Comment by MattLish** [comment]
So, this is caused when the user has reinstalled Wildlander, there will be no ENB files in Stock Game but none copied because it thinks they already exist.
https://github.com/Wildlander-mod/Launcher/pull/445 should solve it
