### ISSUE TITLE
Resolution is incorrect when using duel monitors

### ISSUE THREAD

**Issue by MattLish** [Wildlander-mod/Launcher#446]
**Describe the bug**
When using duel monitors, the available resolutions in the drop-down are incorrect. 

**To Reproduce**
Enable duel monitors and observe the resolution drop-down.

**Expected behavior**
- The drop-down should show resolutions from the primary monitor
- Changing monitor should show the new resolutions (cache needs disabling).

**Comment by Bejasc** [comment]
Talk in the Discord that disabling/unplugging the second monitor resolves this.

I have tried 
- "Show only on 1" 
- Unplug HDMI from Monitor
- Unplug HDMI from PC
- Power off Monitor (Including remove cord)

Relaunching the Launcher each time, but the resolution options do not change.

I expect to see 1920x1080, but the highest option available is 1680x1050.

**Comment by MattLish** [comment]
@Bejasc thanks for the additional information.
The resolutions are cached after they are first grabbed which would explain why none of the above steps fixed the issue. 
Perhaps that is a mistake given that users could change their screens, have multiple displays, etc.

Disabling the second monitor and uninstalling then installing the launcher should fix this if you need an immediate way to get it working. 
I'll try get a fix out for this ASAP.

(Also, FWIW, I notice you can write TypeScript so feel free to get involved and help out with the launcher if you would like :) )

**Comment by MattLish** [comment]
As a workaround, users can extend their display from the primary monitor which should display the correct resolutions

**Comment by MattLish** [comment]
Closing as it hasn't been reported for a long time and cannot be reproduced
