### ISSUE TITLE
Multiple reports of launcher failing to open after a update.

### ISSUE THREAD

**Issue by Mieekaserra** [Wildlander-mod/Launcher#449]
**Describe the bug**
Multiple reports of launcher failing to open after a update.

**Screenshots**
![image](https://user-images.githubusercontent.com/26418143/149628819-2a00bd78-d1d6-40b4-8e74-905a291b84cf.png)

**Additional context**
users can resolve by uninstalling and reinstalling.

**Comment by Mieekaserra** [comment]
Seems to be getting stuck because it cant delete some ENB files. 

Perhaps they are opening it after bombing out of skyrim ?

**Comment by MattLish** [comment]
This hasn't happened for a while, closing and can reopen if new issues occur
