### ISSUE TITLE
Detect windows 7 and provide user with a warning

### ISSUE THREAD

**Issue by TaranRoth** [Wildlander-mod/Launcher#455]

**Comment by Mieekaserra** [comment]
Hi Matt - I cant reply on discord.

When you hit the launch button on windows 7, or try to open mod organiser. nothing happens.

**Comment by Mieekaserra** [comment]
Windows 7 does not have the application support architecture to run Universal Windows Platform applications 

https://cdn.discordapp.com/attachments/881254575640838254/933758332601245766/main.log

they click the launch button then it just hangs.

**Comment by Campiotti** [comment]
Can be done with
```js
import os from "os";

const release = os.release();

return ! release.startsWith("7")
```

Beware of this though https://github.com/electron/electron/issues/3012#issuecomment-538424190
But if we're only excluding 7 and not specifically checking for 10 then it should be fine I think.

**Comment by Campiotti** [comment]
Should be fine to close this now that #504 was solved, right? @MattLish

**Comment by MattLish** [comment]
Correct, it is no longer needed
