### ISSUE TITLE
Detect webroot antivirus running

### ISSUE THREAD

**Issue by Mieekaserra** [Wildlander-mod/Launcher#476]
Webroot antivirus currently causes a CTD when it detects the .netcrashlogging trying to inject itself into Skyrimse.exe.

Webroot has no exception list for this behaviour and contact by Meh321 for a option - only have been met with his words "rude" refusals. 

Thereforee the only want to currently run this is to Shut webroot down from the system tray.

Ideally, on launch the launcher should check if webroot is running and tell the user that they need to shut it down first as it is incompatible with modded skyrim.

**Comment by MattLish** [comment]
What is the name of the process we need to detect?
@RingComics Do you know this? I think you said you have a laptop with it running.

**Comment by RingComics** [comment]
Process names:
- WRCoreService.x64.exe
- WRSA.exe
- WRSkyClient.x64.exe
- WRSvcHost.x64.exe
These all run with webroot
