### ISSUE TITLE
Disable Nightvision Fix when "No Shaders" is selected

### ISSUE THREAD

**Issue by Dylan-Perry** [Wildlander-mod/Launcher#501]
ENB's and night vision do not mix by default, but we utilize a plugin that allows them to function together (NightEyeENBFix_PredatorVision.esp). 

This plugin breaks night vision when users are NOT using an ENB (e.g. the "No Shaders" profile), and therefore needs disabling on the "No Shaders" ENB profile.

**Comment by MattLish** [comment]
To test this:

- Make a kadjiit
- Activate night vision
- If the screen is blue, it's broken

**Comment by MattLish** [comment]
To implement this:
MO2 will ignore any plugin that doesn't exist (although it shows an error).

- Rename the night vision fix to include `.HIDDEN ` in the name at the end. e.g. `game-files\mods\Rudy ENB Cathedral Weathers ADDONS and REQUiRED Files\NightEyeENBFix_PredatorVision.esp.Hidden`
