### ISSUE TITLE
Enable ultrawide mods when an ultrawide resolution is selected in the resolution dropdown

### ISSUE THREAD

**Issue by Dylan-Perry** [Wildlander-mod/Launcher#502]
To support ultrawide, we need to enable specific mods - regardless of which performance profile / shader profile the user has selected. 

(For example, if the user's selected resolution is 3440×1440, we need to enable X mod(s). If they keep this resolution but change their performance profile (say, from High to Medium), the ultrawide mod(s) need to stay enabled.)

**Comment by MattLish** [comment]
Handled in #562
