### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by MattLish** [Wildlander-mod/Launcher#506]
The lackluster logging causes difficulty in debugging user errors. 

We need to add:

- OS version
- Game version
- If customisation has been applied
- PowerShell version
- Info on what actions user is taking

**Comment by Mieekaserra** [comment]
Path - Environment variable.

had a user who was missing powershell from windows path which prevented launcher from firing

**Comment by MattLish** [comment]
Could be useful: https://github.com/sindresorhus/electron-util#debuginfo

**Comment by MattLish** [comment]
Duplicate of #533
