### ISSUE TITLE
Add installed wildlander version

### ISSUE THREAD

**Issue by Mieekaserra** [Wildlander-mod/Launcher#522]
Should be able to get this from wabbajack  installed_modlists.json

**Comment by MattLish** [comment]
Note: if a user renames one of the directories, installed_modlists.json will no longer be pointing to the correct location

**Comment by MattLish** [comment]
The launcher will need to detect if the selected path cannot be found and advise the user to rerun WJ pointing to the new path

**Comment by MattLish** [comment]
If the modpath is unknown to WJ (not in `installed_modlists.json`) then thee game version just needs setting to "unknown".

An example of a valid workflow unknown to WJ is a network drive used to play Skyrim or edit records.
