### ISSUE TITLE
Add context menu

### ISSUE THREAD

**Issue by MattLish** [Wildlander-mod/Launcher#593]
There is currently no context menu. 
One can easily be added with https://github.com/sindresorhus/electron-context-menu

**Comment by RingComics** [comment]
What would we want to add to the context menu? I can't think of anything especially useful but I like the idea

**Comment by MattLish** [comment]
@RingComics I think we just add the package which gives us some nice stuff by default:
> `Cut`/`Copy`/`Paste` for text, `Save Image` for images, and `Copy Link` for links. It also adds an `Inspect Element` menu item when in development to quickly view items in the inspector like in Chrome.
