### ISSUE TITLE
File not found: "NetscriptFramework.SkyrimSE.1_6_353_0.bin" error message.

### ISSUE THREAD

**Issue by Ksiphenos** [Wildlander-mod/Launcher#619]
**Describe the bug**
Upon launch, I get this error after booting of the mod organizer. I could play with 0 problems just 5 hours ago, it seems weird to get a netscriptframework error out of nowhere like this.

**To Reproduce**
Steps to reproduce the behavior: Simply launch the game through launcher

**Screenshots**
attached below

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Additional context**
![Ekran Alıntısı](https://user-images.githubusercontent.com/109536917/179544429-34fd5b5f-05b5-4078-bd49-8e8afaf6f21a.JPG)

**Comment by MattLish** [comment]
Hi @Ksiphenos , apologies it has taken me so long to get back to you.

Did you manage to resolve this?
Does the game launch via MO2 directly?
Have you modified your install at all?

**Comment by Ksiphenos** [comment]
Hello, sorry for late reply, apparently it was a problem with my
anniversary edition update and stuff, not very sure how those all work tbh.
I managed to solve it by replacing some game files with the ones from the
wildlander folder. Thanks for your concern, not a very active github user
so i probably missed if you replied my entry.

27 Tem 2022 Çar 17:59 tarihinde Matt Lishman ***@***.***>
şunu yazdı:

**Comment by MattLish** [comment]
Ah, glad you got it working.
That's great, sounds like it isn't an issue with the launcher particularly.
Also, probably not something the launcher could circumvent, likely a Wabbajack problem to solve.

Thanks for getting back to me, I am going to close this issue now but please feel free to reopen if you think it is still an issue
