### ISSUE TITLE
"Error checking for update" when not connected to internet

### ISSUE THREAD

**Issue by ville-v** [Wildlander-mod/Launcher#660]
**Describe the bug**
Unnecessary error when starting the launcher while not connected to internet.

![launcher error](https://user-images.githubusercontent.com/22340294/191995792-03eac1c0-1b64-421d-bb3f-9c62258c2f5d.png)

The error is unnecessary, because if the user is accidentally offline, they will realize it because of errors in the main window:

![launcher main window](https://user-images.githubusercontent.com/22340294/191995988-ff99ae92-d6a4-45dc-98e0-10ce41ca28d9.png)

**To Reproduce**
1. Go offline
2. Start the launcher

**Expected behavior**
Simple fix: Disable the error completely. 

Elegant fix: Detect if Steam is in offline mode, don't show errors about failed downloads when in offline mode.

**Desktop:**
 - OS: Windows 10
 - Version 2.10.0

**Comment by MattLish** [comment]
Apologies, I missed this issue. However, I implemented a check a while back that will just warn the user instead of failing. So this should now be fixed :)
