### ISSUE TITLE
Launcher wIll not launch game

### ISSUE THREAD

**Issue by davestockton** [Wildlander-mod/Launcher#674]
After pressing Launch Game button, I get an error message box:

"Error launching game"
"TypeError: Cannot set properties of undefined (setting 'lock_gui')

I rebooted; same issue.

I uninstalled Launcher and reinstalled; same issue.

Was working last night with seemingly normal startup and normal shutdown.

**Comment by MattLish** [comment]
@davestockton Apologies, I missed this issue. Do you still experience this problem?
