### ISSUE TITLE
Changes in game are being overwritten on restart of the launcher.

### ISSUE THREAD

**Issue by Mieekaserra** [Wildlander-mod/Launcher#683]
User changes some settings in game - E.G disables save on wait.

Next time the launcher opens, those settings are restored back to the defaults.

**Comment by MattLish** [comment]
@Mieekaserra  Where are these settings stored? Are we sure this is the launcher? I can't imagine these settings being impacted by the launcher.

**Comment by Mieekaserra** [comment]
Lets say a user edits the Autosave in game. That writes away to the profile Skyrimprefs.ini
next time they open or launch the game - not sure which (could be both)
you OVERWRITE that changed Skyrimprefs.ini from the files in the Launcher\graphics presets

Its pretty much the same with any setting in game - next time they play its reverted to defaults

The only way the user has been able to edit any of the settings in game is by manually editing the Launcher\graphics presets version of skyrim or skyrimprefs.ini

**Comment by MattLish** [comment]
This can be solved in the same way we manage enbs. When the game closes, the file can be copied back to the launcher location so it can be reused next time.
