### ISSUE TITLE
Prevent home page from reloading Patreon and news every time

### ISSUE THREAD

**Issue by MattLish** [Wildlander-mod/Launcher#75]
Currently, navigating to the home tab causes a refetch of the Patreon and news data. This should be cached to prevent nothing appearing while it's loaded each time.

**Comment by phinocio** [comment]
Caching, then fetching every like ..5-10m, or an hour or something, might be a good idea. 

The server the API is hosted on is very simple/cheap, and a ton of people (like on release of SSE or something) trying to fetch it all at once, possibly multiple times as they look around the app, could cause issues depending on how many people it is.

There's also the fact Dylan doesn't post that many patreon posts (as it is right now, at least), and, personally, I feel someone showing up in the list *the second* they pledge, isn't *that* important.

And the most important part of that - as it stands right now, the API only updates once a day anyway :P (Nazeem has an admin command to force an update, though, if needed).
